/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSupplySyncRouteImport } from './routes/projects.supply-sync'
import { Route as ProjectsNebulaConsoleRouteImport } from './routes/projects.nebula-console'
import { Route as ProjectsAtlasNotesRouteImport } from './routes/projects.atlas-notes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSupplySyncRoute = ProjectsSupplySyncRouteImport.update({
  id: '/projects/supply-sync',
  path: '/projects/supply-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNebulaConsoleRoute = ProjectsNebulaConsoleRouteImport.update({
  id: '/projects/nebula-console',
  path: '/projects/nebula-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAtlasNotesRoute = ProjectsAtlasNotesRouteImport.update({
  id: '/projects/atlas-notes',
  path: '/projects/atlas-notes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/atlas-notes': typeof ProjectsAtlasNotesRoute
  '/projects/nebula-console': typeof ProjectsNebulaConsoleRoute
  '/projects/supply-sync': typeof ProjectsSupplySyncRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/atlas-notes': typeof ProjectsAtlasNotesRoute
  '/projects/nebula-console': typeof ProjectsNebulaConsoleRoute
  '/projects/supply-sync': typeof ProjectsSupplySyncRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/atlas-notes': typeof ProjectsAtlasNotesRoute
  '/projects/nebula-console': typeof ProjectsNebulaConsoleRoute
  '/projects/supply-sync': typeof ProjectsSupplySyncRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/atlas-notes'
    | '/projects/nebula-console'
    | '/projects/supply-sync'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/atlas-notes'
    | '/projects/nebula-console'
    | '/projects/supply-sync'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects/atlas-notes'
    | '/projects/nebula-console'
    | '/projects/supply-sync'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAtlasNotesRoute: typeof ProjectsAtlasNotesRoute
  ProjectsNebulaConsoleRoute: typeof ProjectsNebulaConsoleRoute
  ProjectsSupplySyncRoute: typeof ProjectsSupplySyncRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/supply-sync': {
      id: '/projects/supply-sync'
      path: '/projects/supply-sync'
      fullPath: '/projects/supply-sync'
      preLoaderRoute: typeof ProjectsSupplySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/nebula-console': {
      id: '/projects/nebula-console'
      path: '/projects/nebula-console'
      fullPath: '/projects/nebula-console'
      preLoaderRoute: typeof ProjectsNebulaConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/atlas-notes': {
      id: '/projects/atlas-notes'
      path: '/projects/atlas-notes'
      fullPath: '/projects/atlas-notes'
      preLoaderRoute: typeof ProjectsAtlasNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAtlasNotesRoute: ProjectsAtlasNotesRoute,
  ProjectsNebulaConsoleRoute: ProjectsNebulaConsoleRoute,
  ProjectsSupplySyncRoute: ProjectsSupplySyncRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
