/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsLearnAndRouteImport } from './routes/projects.learn-and'
import { Route as ProjectsBreastCancerCnnRouteImport } from './routes/projects.breast-cancer-cnn'
import { Route as ProjectsAglaeaRouteImport } from './routes/projects.aglaea'
import { Route as ProjectsAgenticRagRouteImport } from './routes/projects.agentic-rag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLearnAndRoute = ProjectsLearnAndRouteImport.update({
  id: '/projects/learn-and',
  path: '/projects/learn-and',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBreastCancerCnnRoute = ProjectsBreastCancerCnnRouteImport.update({
  id: '/projects/breast-cancer-cnn',
  path: '/projects/breast-cancer-cnn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAglaeaRoute = ProjectsAglaeaRouteImport.update({
  id: '/projects/aglaea',
  path: '/projects/aglaea',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAgenticRagRoute = ProjectsAgenticRagRouteImport.update({
  id: '/projects/agentic-rag',
  path: '/projects/agentic-rag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/agentic-rag': typeof ProjectsAgenticRagRoute
  '/projects/aglaea': typeof ProjectsAglaeaRoute
  '/projects/breast-cancer-cnn': typeof ProjectsBreastCancerCnnRoute
  '/projects/learn-and': typeof ProjectsLearnAndRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/agentic-rag': typeof ProjectsAgenticRagRoute
  '/projects/aglaea': typeof ProjectsAglaeaRoute
  '/projects/breast-cancer-cnn': typeof ProjectsBreastCancerCnnRoute
  '/projects/learn-and': typeof ProjectsLearnAndRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/agentic-rag': typeof ProjectsAgenticRagRoute
  '/projects/aglaea': typeof ProjectsAglaeaRoute
  '/projects/breast-cancer-cnn': typeof ProjectsBreastCancerCnnRoute
  '/projects/learn-and': typeof ProjectsLearnAndRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/agentic-rag'
    | '/projects/aglaea'
    | '/projects/breast-cancer-cnn'
    | '/projects/learn-and'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/agentic-rag'
    | '/projects/aglaea'
    | '/projects/breast-cancer-cnn'
    | '/projects/learn-and'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects/agentic-rag'
    | '/projects/aglaea'
    | '/projects/breast-cancer-cnn'
    | '/projects/learn-and'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAgenticRagRoute: typeof ProjectsAgenticRagRoute
  ProjectsAglaeaRoute: typeof ProjectsAglaeaRoute
  ProjectsBreastCancerCnnRoute: typeof ProjectsBreastCancerCnnRoute
  ProjectsLearnAndRoute: typeof ProjectsLearnAndRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/learn-and': {
      id: '/projects/learn-and'
      path: '/projects/learn-and'
      fullPath: '/projects/learn-and'
      preLoaderRoute: typeof ProjectsLearnAndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/breast-cancer-cnn': {
      id: '/projects/breast-cancer-cnn'
      path: '/projects/breast-cancer-cnn'
      fullPath: '/projects/breast-cancer-cnn'
      preLoaderRoute: typeof ProjectsBreastCancerCnnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/aglaea': {
      id: '/projects/aglaea'
      path: '/projects/aglaea'
      fullPath: '/projects/aglaea'
      preLoaderRoute: typeof ProjectsAglaeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/agentic-rag': {
      id: '/projects/agentic-rag'
      path: '/projects/agentic-rag'
      fullPath: '/projects/agentic-rag'
      preLoaderRoute: typeof ProjectsAgenticRagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAgenticRagRoute: ProjectsAgenticRagRoute,
  ProjectsAglaeaRoute: ProjectsAglaeaRoute,
  ProjectsBreastCancerCnnRoute: ProjectsBreastCancerCnnRoute,
  ProjectsLearnAndRoute: ProjectsLearnAndRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
